Feature/infos diplomes candidats
TLS-SEC/tls-sec.github.io pull request #1
Opened 2017-09-04 10:03 UTC by carlosaguilarmelchor

2017-09-05 08:33 UTC, pcplpc requested changes
See: [patch.txt](https://github.com/TLS-SEC/tls-sec.github.io/files/1276630/patch.txt)
```
wget https://github.com/TLS-SEC/tls-sec.github.io/files/1276630/patch.txt
git apply patch.txt
git diff --word-diff
```

*Informations pour les candidats à TLS-SEC :*
```
Pour toute information complémentaire contactez Carlos Aguilar [-à-]{+sur+} son adresse [-mail-]{+mail :+} *prénom point nom* [-dans-]{+avec+} le domaine *enseeiht point fr*.
```

*Diplômes :*
```
Le diplôme auquel vous pouvez prétendre dépend de votre situation au moment de votre candidature [-(c'est à dire-]{+(c'est-à-dire+} l'année avant TLS-SEC).
```

*Étudiant en avant-dernière année d'école d'ingénieur :*
```
[-**Important:**-]{+**Important :**+} Les étudiants en contrat de professionnalisation ne pourront obtenir que le diplôme d'ingénieur (le contrat est incompatible avec une inscription en M2 dans nos écoles d'ingénieurs).

[-**Important:**-]{+**Important :**+} Si vous êtes dans une école qui n'est pas partenaire il est aussi possible de [-candidater-]{+postuler+} au même titre que les étudiants d'écoles partenaires. Il faudra [-juste-]{+seulement+} obtenir un accord entre l'INP ENSEEIHT et l'école de départ pour faire une année d'échange. Vous pouvez dans ce cas obtenir le diplôme d'ingénieur et de Master.
```

*Autres étudiants :*
```
Tout autre étudiant (venant d'une université, ayant déjà obtenu son diplôme d'ingénieur, venant d'une entreprise), qu'il relève de la formation continue ou initiale, devra avoir un niveau BAC+5 (ou BAC+4 justifiant de trois années d'expérience professionnelle). Il pourra obtenir un Mastère Spécialisé (BAC+6) en suivant les cours [-ingénieur-]{+d'ingénieur+} plus environ une centaine d'heures d'enseignement. 

Les frais d'inscription au Mastère Spécialisé sont de 4500 euros pour les étudiants [-relevant de la-]{+en+} formation initiale et de 12000 euros pour les étudiants [-relevant de la-]{+en+} formation continue. Les apprentis diplômés par l'une des écoles d'ingénieurs partenaires l'année de leur candidature à TLS-SEC, peuvent prétendre aux frais d'inscription de la formation initiale (au cas par cas).
```

2017-09-05 08:50 UTC, toffan commented on index.md
> +TLS-SEC permet d'obtenir un diplôme d'ingénieur, un Master, ou un Mastère Spécialisé. Le diplôme auquel vous pouvez prétendre dépend de votre situation initiale et des cours que vous suivez. Plus d'i
Pas clair que ça permet d'obtenir un double diplôme. Peut-être « TLS-SEC permet d'obtenir un Master ou un Mastère Spécialisé ainsi que de valider la dernière année de votre diplôme d'ingénieur. » si j'ai bien compris ce que tls-sec permet.

2017-09-05 08:50 UTC, toffan commented on candidats.md
> +#### Étudiant en avant-dernière année d'école d'ingénieur
ou « Étudiants en 4e année de cycle ingénieur »

2017-09-05 08:50 UTC, toffan commented on candidats.md
> +Tout autre étudiant (venant d'une université, ayant déjà obtenu son diplôme d'ingénieur, venant d'une entreprise), qu'il relève de la formation continue ou initiale, devra avoir un niveau BAC+5 (ou B
Dans la première parenthèse: Remplacer la dernière virgule par un « ou » ou bien ajouter «, etc. » à la fin.

2017-09-05 08:50 UTC, toffan commented on candidats.md
> +#### Autres étudiants
C'est pas que pour les étudiants, c'est aussi pour les professionnels. Je remplacerais par « Autres étudiants ou professionnels »

2017-09-05 08:50 UTC, toffan commented on candidats.md
> +#### Apprenti en avant-dernière année d'école d'ingénieur
ou « Apprenti en 4e année de cycle ingénieur »

2017-09-05 08:51 UTC, carlosaguilarmelchor commented
Merci ! Done.

2017-09-05 08:55 UTC, plcp commented on index.md
> +TLS-SEC permet d'obtenir un diplôme d'ingénieur, un Master, ou un Mastère Spécialisé. Le diplôme auquel vous pouvez prétendre dépend de votre situation initiale et des cours que vous suivez. Plus d'i
Forme alternative : « TLS-SEC permet d'obtenir un diplôme d'ingénieur avec un Master ou un Mastère Spécialisé. »
(si j'ai bien compris ce que TLS-SEC offre)

2017-09-05 08:56 UTC, carlosaguilarmelchor commented on index.md
> +TLS-SEC permet d'obtenir un diplôme d'ingénieur, un Master, ou un Mastère Spécialisé. Le diplôme auquel vous pouvez prétendre dépend de votre situation initiale et des cours que vous suivez. Plus d'i
Ok mais je vais faire une autre formulation car le diplôme d'ingé c'est pas toujours le cas

2017-09-05 08:56 UTC, pcplpc approved these changes

2017-09-05 08:56 UTC, carlosaguilarmelchor commented on candidats.md
> +#### Étudiant en avant-dernière année d'école d'ingénieur
ok

2017-09-05 08:56 UTC, carlosaguilarmelchor commented on candidats.md
> +#### Autres étudiants
ok

2017-09-05 08:59 UTC, carlosaguilarmelchor commented
Merci @toffan done !

2017-09-05 13:29 UTC, nicomett approved these changes

2017-09-05 18:53 UTC, damiencassu approved these changes

2017-09-06 07:45 UTC, carlosaguilarmelchor commented
Thx all for the validations. 
Merging.

2017-09-06 07:45 UTC, merged