ajout pres phreaking
TLS-SEC/tls-sec.github.io pull request #8
Opened 2017-11-24 19:36 UTC by pcsec

2017-11-28 10:15 UTC, carlosaguilarmelchor requested changes
Salut :)
est-ce que tu peux modifier aussi le fichier RHE.md comme ont fait les autres stp ? 
merci !

2017-11-30 09:28 UTC, carlosaguilarmelchor commented
@pcsec t'es par là ?

2017-12-19 18:20 UTC, pcsec commented
Vraiment désolé pour le retard.
Le fichier TLS-SEC/tls-sec.github.io/rhes.md ?

2017-12-19 19:47 UTC, carlosaguilarmelchor commented
Plus la peine. Ton RHE et la modif du fichier en question ont etais commit dans la PR#10

2017-12-19 19:47 UTC, closed without merging